In [12]:
import numpy as np

# Создаём вектора
vector1 = np.arange(0, 1.5, 0.1)
vector2 = np.arange(1, 7)

print(vector1)
print(vector2)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4]
[1 2 3 4 5 6]


In [13]:
# Создаём матрицы
matrix1 = vector1.reshape(5, 3)
matrix2 = vector2.reshape(3, 2)

print(matrix1)
print(matrix2)

[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]
 [0.9 1.  1.1]
 [1.2 1.3 1.4]]
[[1 2]
 [3 4]
 [5 6]]


In [14]:
# Выполняем умножение матриц
result = np.dot(matrix1, matrix2)
print(result)

[[ 1.3  1.6]
 [ 4.   5.2]
 [ 6.7  8.8]
 [ 9.4 12.4]
 [12.1 16. ]]
