In [1]:
import numpy as np

A = np.matrix([[1,2,1],[-2,1,1]])
B = np.matrix([[3,1],[-1,0],[2,4]])
C = np.matrix([[-2,2],[1,-1],[1,2]])

In [2]:
def matrices_summ(matrix1,matrix2):
  # Прооверяем что матрицы имеют одинаковый размер
  if matrix1.shape != matrix2.shape:
    raise ValueError("Матрицы должны быть одинакового размера")
  # Создаем пустую матрицу для результата
  matrix1_plus_matrix2=np.zeros_like(matrix1)
  # Умножаем матрицу2 на 2
  matrix2_2_times = matrix2 * 2
  # Суммируем 2 матрицы
  sum_matrices = np.add(matrix1, matrix2_2_times)
  return sum_matrices

In [3]:
"""Так как матрицы не совместимы, матрицу B приведём к форме
 матрицы А"""
result1 = matrices_summ(A,B.reshape((2,3)))
print(result1)

[[ 7  4 -1]
 [-2  5  9]]


In [4]:
"""В данном случае матрицы одинаковые по форме, из-за этого
переобразование не требуется"""
result2 = matrices_summ(B,C)
print(result2)

[[-1  5]
 [ 1 -2]
 [ 4  8]]
