In [14]:
import numpy as np

# Создаем матрицу 8x8, заполненную нулями
matrix = np.zeros((8, 8), dtype=int)
print(matrix)

# Заполняем матрицу значениями 1 и 0 в шахматном порядке с использованием срезов
matrix[1::2, ::2] = 1
matrix[::2, 1::2] = 1

# Выводим матрицу на экран
print("\n")
for row in matrix:
    print(' '.join(map(str, row)))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


0 1 0 1 0 1 0 1
1 0 1 0 1 0 1 0
0 1 0 1 0 1 0 1
1 0 1 0 1 0 1 0
0 1 0 1 0 1 0 1
1 0 1 0 1 0 1 0
0 1 0 1 0 1 0 1
1 0 1 0 1 0 1 0


In [12]:
"""С использованием срезов, результат, почему-то немного отличается
от того, что приведено в примере ДЗ"""
import numpy as np

# Создаем матрицу 8x8, заполненную нулями
matrix = np.zeros((8, 8), dtype=int)
print(matrix)

# Заполняем матрицу значениями 1 и 0 в шахматном порядке
for i in range(8):
    for j in range(8):
        if (i + j) % 2 == 0:
            matrix[i][j] = 1

# Выводим итоговую матрицу
print("\n")
print(matrix)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]
